grid_map_topic: /offline_
grid_map_visualizations:
  - name: map_points
    type: point_cloud
    params:
     layer: offline
  - name: map_
    type: occupancy_grid
    params:
     layer: offline
     data_min: 0
     data_max: 1
