system/v_max: 0.2
system/dyaw_max: 0.75
system/camera/pitch: [15.0]
system/camera/horizontal: [90.0]
system/camera/vertical: [60.0]
system/bbx/x: 0.5
system/bbx/y: 0.5
system/bbx/z: 0.3
system/bbx/overshoot: 0.5

nbvp/gain/free: 0.0
nbvp/gain/occupied: 0.0
nbvp/gain/unmapped: 1.0
nbvp/gain/area: 0.0
nbvp/gain/probabilistic: 0.0
nbvp/gain/range: 1
nbvp/gain/zero: 0.0
nbvp/gain/degressive_coeff: 0.5
nbvp/tree/extension_range: 1.0
nbvp/tree/exact_root: false
nbvp/tree/initial_iterations: 1
nbvp/tree/cuttoff_iterations: 200
nbvp/dt: 0.1

nbvp/log/throttle: 0.25
nbvp/log/on: true

# bounding box: necessary to limit the simulation 
# scenario (smaller than actual gazebo scenario)
bbx/minX: -12.0
bbx/minY: -12.0
bbx/minZ: -0.0
bbx/maxX: 12.0
bbx/maxY: 12.0
bbx/maxZ: 3.0
bbx/softBounds: false

pcl_throttle: 0.25
inspection_throttle: 0.5

#Mavros related settings
/iris/mavros/local_position/frame_id: world           #(string, default: fcu) frame_id for message.
/iris/mavros/local_position/tf/send: true             #(bool, default: true)
/iris/mavros/local_position/tf/frame_id: world        #(string, default: local_origin) Origin frame_id for TF.
/iris/mavros/local_position/tf/child_frame_id: fcu    #(string, default: fcu) Child frame_id for TF.

