grid_map_topic: /Nav_map
grid_map_visualizations:
  - name: map_point
    type: point_cloud
    params:
     layer: Victim_Nav
  - name: map_
    type: occupancy_grid
    params:
     layer: Victim_Nav
     data_min: 0
     data_max: 1


