grid_map_topic: /temp_map
grid_map_visualizations:
  - name: map_point
    type: point_cloud
    params:
     layer: temp
  - name: map_
    type: occupancy_grid
    params:
     layer: temp
     data_min: 0
     data_max: 1


