grid_map_topic: /victim_map/grid_map_DL
grid_map_visualizations:
  - name: elevation_map_points
    type: point_cloud
    params:
     layer: victim_DL
  - name: elevation_grid
    type: occupancy_grid
    params:
     layer: victim_DL
     data_min: 0
     data_max: 1

grid_map_topic: /victim_map/grid_map_thermal
grid_map_visualizations:
  - name: elevation_map_points1
    type: point_cloud
    params:
     layer: victim_thermal
  - name: elevation_grid1
    type: occupancy_grid
    params:
     layer: victim_thermal
     data_min: 0
     data_max: 1

grid_map_topic: /temp_map
grid_map_visualizations:
  - name: elevation_map_points2
    type: point_cloud
    params:
     layer: temp
  - name: elevation_grid2
    type: occupancy_grid
    params:
     layer: temp
     data_min: 0
     data_max: 1


